import { z } from "zod";
declare const userSchema: z.ZodObject<{
    email: z.ZodString;
    password: z.ZodString;
    mobile: z.ZodString;
    firstName: z.ZodString;
    lastName: z.ZodString;
}, z.core.$strip>;
declare const updateUserSchema: z.ZodObject<{
    mobile: z.ZodString;
    firstName: z.ZodString;
    lastName: z.ZodString;
}, z.core.$strip>;
declare const userProfileSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    address: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    avatar: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    organization: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    contactNumber: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    contactEmail: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    website: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    country: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    state: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    city: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    businessId: z.ZodNumber;
    userId: z.ZodNumber;
    about: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
declare const loginSchema: z.ZodObject<{
    email: z.ZodString;
    password: z.ZodString;
}, z.core.$strip>;
declare const customerSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    name: z.ZodString;
    email: z.ZodString;
    phone: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    cusCode: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    address: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    city: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    state: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    country: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    postalCode: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isActive: z.ZodOptional<z.ZodBoolean>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    businessId: z.ZodNumber;
}, z.core.$strip>;
declare const itemSchema: z.ZodObject<{
    name: z.ZodString;
    description: z.ZodString;
    category: z.ZodString;
    proCode: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    sku: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    unitPrice: z.ZodNumber;
    costPrice: z.ZodNumber;
    unit: z.ZodDefault<z.ZodString>;
    taxRate: z.ZodDefault<z.ZodNumber>;
    discountRate: z.ZodDefault<z.ZodNumber>;
    image: z.ZodDefault<z.ZodString>;
    catId: z.ZodNumber;
    stockQuantity: z.ZodDefault<z.ZodNumber>;
    minStockLevel: z.ZodDefault<z.ZodNumber>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    businessId: z.ZodNumber;
}, z.core.$strip>;
declare const codesSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    businessId: z.ZodNumber;
    codeType: z.ZodString;
    codeName: z.ZodString;
    codeDesc: z.ZodOptional<z.ZodString>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    longDesc: z.ZodOptional<z.ZodJSONSchema>;
}, z.core.$strip>;
declare const invoiceMasterSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    invoiceNumber: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    customerId: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    customerPhone: z.ZodString;
    businessId: z.ZodNumber;
    customerName: z.ZodOptional<z.ZodString>;
    customerEmail: z.ZodOptional<z.ZodString>;
    customerAddress: z.ZodOptional<z.ZodString>;
    invoiceDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    dueDate: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    subtotal: z.ZodNumber;
    tax: z.ZodNumber;
    discount: z.ZodNumber;
    deliveryCharge: z.ZodNumber;
    totalAmount: z.ZodNumber;
    status: z.ZodDefault<z.ZodEnum<{
        paid: "paid";
        credit: "credit";
        unpaid: "unpaid";
        archive: "archive";
    }>>;
    notes: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    createdBy: z.ZodNumber;
    paymentInfo: z.ZodOptional<z.ZodObject<{}, z.core.$strip>>;
}, z.core.$strip>;
declare const invoiceCustomerUpdateSchema: z.ZodObject<{
    customerId: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    customerPhone: z.ZodString;
    customerName: z.ZodOptional<z.ZodString>;
    customerEmail: z.ZodOptional<z.ZodString>;
    customerAddress: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
declare const invoiceDetailsSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    invoiceMasterId: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    itemId: z.ZodNumber;
    itemName: z.ZodString;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    quantity: z.ZodNumber;
    unitPrice: z.ZodNumber;
    tax: z.ZodDefault<z.ZodNumber>;
    discount: z.ZodDefault<z.ZodNumber>;
    lineTotal: z.ZodDefault<z.ZodNumber>;
    businessId: z.ZodNumber;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
}, z.core.$strip>;
declare const InvoiceItemsSchema: z.ZodArray<z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    invoiceMasterId: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    itemId: z.ZodNumber;
    itemName: z.ZodString;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    quantity: z.ZodNumber;
    unitPrice: z.ZodNumber;
    tax: z.ZodDefault<z.ZodNumber>;
    discount: z.ZodDefault<z.ZodNumber>;
    lineTotal: z.ZodDefault<z.ZodNumber>;
    businessId: z.ZodNumber;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
}, z.core.$strip>>;
declare const purchaseClientSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    name: z.ZodString;
    email: z.ZodString;
    phone: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    address: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    city: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    state: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    country: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    postalCode: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    contactPerson: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    taxId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    paymentTerms: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    businessId: z.ZodNumber;
}, z.core.$strip>;
declare const PurchaseSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    purchaseNumber: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    supplierId: z.ZodNumber;
    supplierName: z.ZodString;
    supplierEmail: z.ZodString;
    supplierAddress: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    supplierPhone: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    businessId: z.ZodNumber;
    purchaseDate: z.ZodString;
    expectedDeliveryDate: z.ZodOptional<z.ZodString>;
    actualDeliveryDate: z.ZodOptional<z.ZodString>;
    subtotal: z.ZodNumber;
    taxAmount: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    discountAmount: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    shippingCost: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    totalAmount: z.ZodNumber;
    status: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
        paid: "paid";
        credit: "credit";
        pending: "pending";
        ordered: "ordered";
        received: "received";
        cancelled: "cancelled";
    }>>>;
    paymentStatus: z.ZodDefault<z.ZodOptional<z.ZodEnum<{
        paid: "paid";
        unpaid: "unpaid";
        partial: "partial";
    }>>>;
    notes: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
    createdBy: z.ZodNumber;
}, z.core.$strip>;
declare const departmentSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    name: z.ZodString;
    deptCode: z.ZodOptional<z.ZodString>;
    businessId: z.ZodNumber;
    createdAt: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodDate]>>;
}, z.core.$strip>;
declare const employeeSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    userName: z.ZodString;
    email: z.ZodString;
    empCode: z.ZodOptional<z.ZodString>;
    businessId: z.ZodNumber;
    password: z.ZodString;
    mobile: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    departmentId: z.ZodOptional<z.ZodNumber>;
    departmentName: z.ZodString;
    hireDate: z.ZodUnion<[z.ZodString, z.ZodDate]>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    createdAt: z.ZodOptional<z.ZodDate>;
    rolePermission: z.ZodOptional<z.ZodJSONSchema>;
}, z.core.$strip>;
declare const PurchaseItemListSchema: z.ZodArray<z.ZodObject<{
    id: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    purchaseId: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    itemId: z.ZodNumber;
    itemName: z.ZodString;
    quantity: z.ZodNumber;
    lineTotal: z.ZodNumber;
    businessId: z.ZodNumber;
    unitPrice: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    unitCost: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    receivedQuantity: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
}, z.core.$strip>>;
declare const SearchSchema: z.ZodObject<{
    businessId: z.ZodNumber;
    searchTerm: z.ZodOptional<z.ZodString>;
    limit: z.ZodNumber;
}, z.core.$strip>;
declare const BusinessStatsSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodNumber>;
    businessId: z.ZodNumber;
    customers: z.ZodDefault<z.ZodNumber>;
    items: z.ZodDefault<z.ZodNumber>;
    employees: z.ZodDefault<z.ZodNumber>;
    invoices: z.ZodDefault<z.ZodNumber>;
    purchases: z.ZodDefault<z.ZodNumber>;
    suppliers: z.ZodDefault<z.ZodNumber>;
}, z.core.$strip>;
declare const ArchiveSchema: z.ZodObject<{
    businessId: z.ZodNumber;
    id: z.ZodNumber;
    isActive: z.ZodBoolean;
}, z.core.$strip>;
export type TUserSchema = z.infer<typeof userSchema>;
export type TLoginSchema = z.infer<typeof loginSchema>;
export type TCustomerSchema = z.infer<typeof customerSchema>;
export type TItemSchema = z.infer<typeof itemSchema>;
export type TCodesSchema = z.infer<typeof codesSchema>;
export type TInvoiceMasterSchema = z.infer<typeof invoiceMasterSchema>;
export type TInvoiceDetailsSchema = z.infer<typeof invoiceDetailsSchema>;
export type TPurchaseClientSchema = z.infer<typeof purchaseClientSchema>;
export type TPurchaseSchema = z.infer<typeof PurchaseSchema>;
export type TPurchaseItemListSchema = z.infer<typeof PurchaseItemListSchema>;
export type TInvoiceItemsSchema = z.infer<typeof InvoiceItemsSchema>;
export type TDepartmentSchema = z.infer<typeof departmentSchema>;
export type TEmployeeSchema = z.infer<typeof employeeSchema>;
export type TInvoiceCustomerUpdateSchema = z.infer<typeof invoiceCustomerUpdateSchema>;
export type TUserProfileSchema = z.infer<typeof userProfileSchema>;
export type TUpdateUserSchema = z.infer<typeof updateUserSchema>;
export type TSearchSchema = z.infer<typeof SearchSchema>;
export type TBusinessStatsSchema = z.infer<typeof BusinessStatsSchema>;
export type TArchiveSchema = z.infer<typeof ArchiveSchema>;
export { userSchema, loginSchema, customerSchema, itemSchema, codesSchema, invoiceMasterSchema, invoiceDetailsSchema, purchaseClientSchema, PurchaseSchema, PurchaseItemListSchema, InvoiceItemsSchema, departmentSchema, employeeSchema, invoiceCustomerUpdateSchema, userProfileSchema, updateUserSchema, SearchSchema, BusinessStatsSchema, ArchiveSchema, };
//# sourceMappingURL=validate.d.ts.map